name: Tests
on: [push, pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - name: Install requirements
        run: pip install flake8 pycodestyle black isort
      - name: Check syntax
        run: flake8 . --count --select=C901,E721,E901,E999,F401,F821,F822,F823,F841 --show-source --statistics --extend-exclude ckan
      - name: Check codestyle
        run: |
          isort --diff --check ckanext/
          black --diff --check ckanext/

  test:
    needs: lint
    strategy:
      matrix:
        ckan-version: ["2.10", "2.11"]
      fail-fast: false

    name: CKAN ${{ matrix.ckan-version }}
    runs-on: ubuntu-latest
    container:
      image: ckan/ckan-dev:${{ matrix.ckan-version }}
    services:
      solr:
        image: ckan/ckan-solr:${{ matrix.ckan-version }}-solr9
      postgres:
        image: ckan/ckan-postgres-dev:${{ matrix.ckan-version }}
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
      redis:
        image: redis:3
    env:
      CKAN_SQLALCHEMY_URL: postgresql://ckan_default:pass@postgres/ckan_test
      CKAN_DATASTORE_WRITE_URL: postgresql://datastore_write:pass@postgres/datastore_test
      CKAN_DATASTORE_READ_URL: postgresql://datastore_read:pass@postgres/datastore_test
      CKAN_SOLR_URL: http://solr:8983/solr/ckan
      CKAN_REDIS_URL: redis://redis:6379/1
      CKAN_SITE_URL: http://test.ckan.net
      COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install requirements
        run: |
          # Replace default path to CKAN core config file with the one on the container
          sed -i -e 's/use = config:.*/use = config:\/srv\/app\/src\/ckan\/test-core.ini/' test.ini
          pip install -r requirements.txt
          pip install -r dev-requirements.txt
          pip install -e .

      - name: Setup extension
        run: |
          ckan -c test.ini db init
          ckan -c test.ini db pending-migrations --apply

      - name: Run tests
        run: nosetests --ckan --nologcapture --with-pylons=test.ini --with-coverage --cover-package=ckanext.subscribe --cover-inclusive --cover-erase --cover-tests ckanext/subscribe

      - name: Coveralls
        run: |
          # Upgrade certi to fix SSL error due to the version installed in CKAN-2.8 image 
          pip install --upgrade certifi
          # Run coveralls command with retry logic to handle potential transient issues
          for attempt in 1 2 3; do
            coveralls && break
            echo "Attempt $attempt: Failed to submit coverage, retrying in 10 seconds..."
            sleep 10
          done
